backend:
	name: git-gateway
	branch: main
media_folder: "public/assets"
public_folder: "/assets"
collections:
	- name: "articles"
	  label: "My Articles"
	  folder: "src/articles"
	  create: true
	  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
	  fields:
		  - { label: "Title", name: "title", widget: "string"}
		  - { label: "Source", name: "source", widget: "string"}
		  - { label: "Date", name: "date", widget: "datetime", date_format: "M/D/YY", time_format:false, picker_utc: false }
		  - { label: "Link", name: "link", widget: "string" }
		  - { label: "Use Logo", name: "logo", widget: "boolean", default: true }
		  - { label: "Image", name: "image", widget: "image" }
			